version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: champions
      MYSQL_USER: kmiura
      MYSQL_PASSWORD: Kmiura1234#
    networks:
      - mynetwork
    volumes:
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql-container
      DB_PORT: 3306
      DB_NAME: champions
      DB_USER: kmiura
      DB_PASSWORD: Kmiura1234#
    networks:
      - mynetwork
    restart: on-failure

networks:
  mynetwork:
    driver: bridge
